//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacingGame.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Controls : global::System.Configuration.ApplicationSettingsBase {
        
        private static Controls defaultInstance = ((Controls)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Controls())));
        
        public static Controls Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::Microsoft.Xna.Framework.Input.Keys Throttle {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Throttle"]));
            }
            set {
                this["Throttle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys TurnLeft {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["TurnLeft"]));
            }
            set {
                this["TurnLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys TurnRight {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["TurnRight"]));
            }
            set {
                this["TurnRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Microsoft.Xna.Framework.Input.Keys StrafeLeft {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["StrafeLeft"]));
            }
            set {
                this["StrafeLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::Microsoft.Xna.Framework.Input.Keys StrafeRight {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["StrafeRight"]));
            }
            set {
                this["StrafeRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::Microsoft.Xna.Framework.Input.Keys LeftBrake {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["LeftBrake"]));
            }
            set {
                this["LeftBrake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::Microsoft.Xna.Framework.Input.Keys RightBrake {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["RightBrake"]));
            }
            set {
                this["RightBrake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftControl")]
        public global::Microsoft.Xna.Framework.Input.Keys FireWeapon {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["FireWeapon"]));
            }
            set {
                this["FireWeapon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public global::Microsoft.Xna.Framework.Input.Keys DiscardWeapon {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["DiscardWeapon"]));
            }
            set {
                this["DiscardWeapon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::Microsoft.Xna.Framework.Input.Keys Boost {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Boost"]));
            }
            set {
                this["Boost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::Microsoft.Xna.Framework.Input.Keys Reverse {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Reverse"]));
            }
            set {
                this["Reverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftShift")]
        public global::Microsoft.Xna.Framework.Input.Keys Jump {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Jump"]));
            }
            set {
                this["Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Microsoft.Xna.Framework.Input.Keys easyThrottle {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["easyThrottle"]));
            }
            set {
                this["easyThrottle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys easyLeft {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["easyLeft"]));
            }
            set {
                this["easyLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys easyRight {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["easyRight"]));
            }
            set {
                this["easyRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Microsoft.Xna.Framework.Input.Keys easyReverse {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["easyReverse"]));
            }
            set {
                this["easyReverse"] = value;
            }
        }
    }
}
